### ISSUE TITLE
Can't work on Elasticsearch 2.1.1 

### ISSUE THREAD

**Issue by joway** [elasticfence/elasticsearch-http-user-auth#1]
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [http-user-auth-plugin] is incompatible with Elasticsearch [2.1.1]. Was designed for version [2.0.0]
    at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:117)
    at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:302)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
    at org.elasticsearch.node.Node.<init>(Node.java:146)
    at org.elasticsearch.node.Node.<init>(Node.java:128)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

how to fix it ?

**Comment by lmangani** [comment]
Hi @joway please use the [2.1 branch](https://github.com/elasticfence/elasticsearch-http-user-auth/tree/2.1) of Elasticfence for Elasticsearch 2.1.1
