### ISSUE TITLE
support for elasticsearch 5.2

### ISSUE THREAD

**Issue by abhinaythurlapati** [elasticfence/elasticsearch-http-user-auth#78]
I would like to use elasticfence for elasticsearch 5.2.0. Since elasticsearch can't install the plugin, I modified the elasticsearch related config in  plugin-descriptor.properties to 5.2. Thus i am able to install the plugin. However starting elasticsearch fails with the following error:
```
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.rest.RestFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[ 
```
I couldn't find the rest directory/class in the org.elasticsearch package. Can you please suggest how to fix this issue or make elasticfence work for elasticsearch-5.2

**Comment by jemacom** [comment]
o/ @abhinaythurlapati 
As you suggest you can elasticsearch to install elasticfence plugin by twisting the config. But a lot of the authentication logic is implemented on top of ```RestFilter``` as you can check [here](https://github.com/elasticfence/elasticsearch-http-user-auth/blob/5.1.2/src/main/java/org/elasticsearch/plugin/elasticfence/AuthRestFilter.java#L24). 
And starting from version 5.2.0 elasticsearch people deprecate [RestFilter](https://github.com/elastic/elasticsearch/pull/21905). So the plugin won't work unless you have the adequate elasticsearch version preferably 5.1.2.

Hope this clarify things for you :wink:
