### ISSUE TITLE
Not able to login or add user

### ISSUE THREAD

**Issue by karnamonkster** [elasticfence/elasticsearch-http-user-auth#79]
Hi, 
A newbie question, I have successfully installed the  plugin to elasticsearch & Kibana Authentication plugin.
Made the changes in the elasticsearch.yml as per the README.
Added user root with password
Started ES & KIbana 
Stuck at the login screen for Kibana.
Which password should i use?

**Comment by karnamonkster** [comment]
Getting the error when i try to login with root user and password
```
TypeError: Uncaught error: Cannot read property 'search' of undefined
    at login (/home/socadmin/kibana-5.6.2-linux-x86_64/plugins/kibana-auth-plugin/server/auth-local-cookie.js:65:13)
    at Object.internals.handler (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/lib/handler.js:96:36)
    at request._protect.run (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/lib/handler.js:30:23)
    at internals.Protect.run (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/lib/protect.js:64:5)
    at exports.execute (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/lib/handler.js:24:22)
    at each (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/lib/request.js:384:16)
    at iterate (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Hoek.once (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/lib/protect.js:52:16)
    at wrapped (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hoek/lib/index.js:875:20)
    at done (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Function.wrapped [as _next] (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hoek/lib/index.js:875:20)
    at Function.internals.continue (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at /home/socadmin/kibana-5.6.2-linux-x86_64/src/server/http/xsrf.js:25:26
    at Items.serial (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/socadmin/kibana-5.6.2-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
```
